import React, { createContext, useState } from "react";

import { ParsedTrackEvent } from "../../types/event";

export type ContextProps = {
  domains: {
    [name: string]: number;
  };
  events: ParsedTrackEvent[];
};

type UpdateContextProps = React.Dispatch<React.SetStateAction<ContextProps>>;

const defaultState = {
  domains: {},
  events: []
};

export const TrackEventsContext = createContext<
  [ContextProps, UpdateContextProps]
>([{ domains: {}, events: [] }, () => {}]);

export const TrackEventsProvider: React.FunctionComponent = props => {
  const [state, setState] = useState<ContextProps>(
    process.env.NODE_ENV === "production" ? defaultState : dev
  );
  return (
    <TrackEventsContext.Provider value={[state, setState]}>
      {props.children}
    </TrackEventsContext.Provider>
  );
};

const dev: { events: ParsedTrackEvent[]; domains: any } = {
  events: [
    {
      sentAt: 1566697846593,
      domain: "https://jvsbarandgrill.com",
      event: "Page View",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://jvsbarandgrill.com/menu",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.28.0",
        time: 1566697846.591,
        distinct_id:
          "16cc5fc38a252f-09ea38d5abaf2-38637706-232800-16cc5fc38a394c",
        $device_id:
          "16cc5fc38a252f-09ea38d5abaf2-38637706-232800-16cc5fc38a394c",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        replace: {},
        href: "https://jvsbarandgrill.com/menu",
        ancestorOrigins: {},
        origin: "https://jvsbarandgrill.com",
        protocol: "https:",
        host: "jvsbarandgrill.com",
        hostname: "jvsbarandgrill.com",
        port: "",
        pathname: "/menu",
        search: "",
        hash: "",
        assign: {},
        reload: {},
        toString: {},
        state: {
          key: "1566697846563"
        },
        key: "1566697846563",
        action: "PUSH",
        token: "af41a95bfb27680b4573da54ab732053"
      }
    },
    {
      sentAt: 1566697825709,
      domain: "https://mixpanel.com",
      event: "mp_page_view",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697825.707,
        distinct_id:
          "16c4963be9164d-08b7e20809962f-37607c05-384000-16c4963be92111c",
        $device_id:
          "16c4963be9164d-08b7e20809962f-37607c05-384000-16c4963be92111c",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        mp_page: "https://mixpanel.com/report/4/insights",
        mp_browser: "Chrome",
        mp_platform: "Mac OS X",
        token: "e1c2eb12c9208b1aa38b85c06b082e0e"
      }
    },
    {
      sentAt: 1566697825873,
      domain: "https://mixpanel.com",
      event: "$web_event",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697825.87,
        distinct_id: "1732309",
        $device_id:
          "16c4963be70358-01cba8675d339d-37607c05-384000-16c4963be71ce1",
        origin_referrer: '"https://mixpanel.com/"',
        origin_domain: "mixpanel.com",
        $user_id: "1732309",
        user_id: 1732309,
        "Project owner billing account ID": 1,
        "first touch landing page url": "https://mixpanel.com/settings/account",
        "Device Pixel Ratio (is it retina?)": 2,
        "Viewport Width": 1356,
        "Viewport Height": 640,
        is_invited_user: false,
        churn_canary_experiment: "churn_canary_b",
        "Billing: events/MTU plan ID": 15803,
        "Billing: events/MTU plan name":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Billing: people plan ID": 13928,
        "Billing: people plan name": "MTU - People",
        "Billing: events/MTU plan term length": 1,
        "Billing: people plan term length": 12,
        "Billing: paid plan types": "events & people",
        "Billing: events/MTU plan ARR": 0,
        "Billing: people plan ARR": 0,
        "Billing: total account ARR": 0,
        "Billing: account status": "unpaid",
        "Billing: MTU add-on packages": [
          "datawarehouse_export_v1",
          "groups_v1"
        ],
        "Billing: services plan ARR": 0,
        "Current Events Plan":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Current People Plan": "MTU - People",
        "Events Plan Value (ARR)": 0,
        "People Plan Value (ARR)": 0,
        "Account Value (ARR)": 0,
        "Events Billing Cycle": "Monthly",
        "People Billing Cycle": "Annual",
        project_id: 4,
        Email: "ryan.hirsch@mixpanel.com",
        "Project Role": "Owner",
        "Date Joined": "05/2019",
        "3-month Pricing Plan Experiment Group": "pricing_page_control1",
        "OOTB Experiment Group": "ootb_control1",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        role: "owner",
        "# of cohorts": 214,
        "VWO Experiments": [],
        $search_engine: "google",
        "Page Name": "customers",
        Platform: "Web",
        $title: "Mixpanel clone / Insights - Mixpanel | Product Analytics",
        $event_type: "pageview",
        $ce_version: 1,
        $host: "mixpanel.com",
        $pathname: "/report/4/insights",
        token: "metrics-1"
      }
    },
    {
      sentAt: 1566697825949,
      domain: "https://mixpanel.com",
      event: "post login pageview",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697825.948,
        distinct_id: 1732309,
        $device_id:
          "16c4963be9438b-019922f9b4bac5-37607c05-384000-16c4963be95f98",
        $user_id: 1732309,
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        token: "63d57fe2a7c24cc48347a6d2f5999e57"
      }
    },
    {
      sentAt: 1566697826168,
      domain: "https://mixpanel.com",
      event: "Viewed report",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697826.164,
        distinct_id: "1732309",
        $device_id:
          "16c4963be70358-01cba8675d339d-37607c05-384000-16c4963be71ce1",
        origin_referrer: '"https://mixpanel.com/"',
        origin_domain: "mixpanel.com",
        $user_id: "1732309",
        user_id: 1732309,
        "Project owner billing account ID": 1,
        "first touch landing page url": "https://mixpanel.com/settings/account",
        "Device Pixel Ratio (is it retina?)": 2,
        "Viewport Width": 1356,
        "Viewport Height": 640,
        is_invited_user: false,
        churn_canary_experiment: "churn_canary_b",
        "Billing: events/MTU plan ID": 15803,
        "Billing: events/MTU plan name":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Billing: people plan ID": 13928,
        "Billing: people plan name": "MTU - People",
        "Billing: events/MTU plan term length": 1,
        "Billing: people plan term length": 12,
        "Billing: paid plan types": "events & people",
        "Billing: events/MTU plan ARR": 0,
        "Billing: people plan ARR": 0,
        "Billing: total account ARR": 0,
        "Billing: account status": "unpaid",
        "Billing: MTU add-on packages": [
          "datawarehouse_export_v1",
          "groups_v1"
        ],
        "Billing: services plan ARR": 0,
        "Current Events Plan":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Current People Plan": "MTU - People",
        "Events Plan Value (ARR)": 0,
        "People Plan Value (ARR)": 0,
        "Account Value (ARR)": 0,
        "Events Billing Cycle": "Monthly",
        "People Billing Cycle": "Annual",
        project_id: 4,
        Email: "ryan.hirsch@mixpanel.com",
        "Project Role": "Owner",
        "Date Joined": "05/2019",
        "3-month Pricing Plan Experiment Group": "pricing_page_control1",
        "OOTB Experiment Group": "ootb_control1",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        role: "owner",
        "# of cohorts": 214,
        "VWO Experiments": [],
        $search_engine: "google",
        "Page Name": "customers",
        Platform: "Web",
        tab: "insights",
        has_integrated_arb: true,
        has_integrated_engage: true,
        "events tally for project": 66698088,
        "people tally for project": 2800844,
        feature_gate_name: "enterprise",
        "Nav Source": "",
        "Nav Group": "",
        is_gdpr: false,
        show_banner: false,
        allow_snippets: true,
        allow_cookies: true,
        allow_tracking: true,
        opt_tracking: "in",
        opt_cookies: "in",
        opt_email: "in",
        timezone: 420,
        token: "metrics-1"
      }
    },
    {
      sentAt: 1566697826170,
      domain: "https://mixpanel.com",
      event: "$opt_in",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697826.168,
        distinct_id:
          "16c4963be9164d-08b7e20809962f-37607c05-384000-16c4963be92111c",
        $device_id:
          "16c4963be9164d-08b7e20809962f-37607c05-384000-16c4963be92111c",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        token: "e1c2eb12c9208b1aa38b85c06b082e0e"
      }
    },
    {
      sentAt: 1566697826171,
      domain: "https://mixpanel.com",
      event: "Viewed report",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697826.169,
        distinct_id:
          "16c4963be9164d-08b7e20809962f-37607c05-384000-16c4963be92111c",
        $device_id:
          "16c4963be9164d-08b7e20809962f-37607c05-384000-16c4963be92111c",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        tab: "insights",
        is_gdpr: false,
        show_banner: false,
        allow_snippets: true,
        allow_cookies: true,
        allow_tracking: true,
        opt_tracking: "in",
        opt_cookies: "in",
        opt_email: "in",
        timezone: 420,
        token: "e1c2eb12c9208b1aa38b85c06b082e0e"
      }
    },
    {
      sentAt: 1566697826689,
      domain: "https://mixpanel.com",
      event: "Viewed Report",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697826.687,
        distinct_id: 1732309,
        $device_id:
          "16c4963be8165b-06547b21ec22f5-37607c05-384000-16c4963be82ba8",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        $user_id: 1732309,
        Dataset: "$mixpanel",
        Email: "ryan.hirsch@mixpanel.com",
        project_id: "4",
        "User ID": 1732309,
        token: "2fd54f3085a7b7d70da94096fc415078"
      }
    },
    {
      sentAt: 1566697827078,
      domain: "https://mixpanel.com",
      event: "Query Start",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697827.076,
        distinct_id: 1732309,
        $device_id:
          "16c4963be8165b-06547b21ec22f5-37607c05-384000-16c4963be82ba8",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        $user_id: 1732309,
        "Data Group Id": null,
        "Segment by a group property": false,
        "Filter by a group property": false,
        "Report name": "insights",
        "report info: title": "",
        "report info: datasets": [],
        "report info: using new query builder": true,
        "report info: # of datasets": 0,
        "report info: type": "line",
        "report info: style": "standard",
        "report info: analysis": "linear",
        "report info: value": "absolute",
        "report info: list of Cohort clauses": [],
        "report info: list of Compare clauses": ["$top_events"],
        "report info: list of Compare operators": ["total"],
        "report info: list of Group By clauses": [],
        "report info: list of Custom Property Group By clauses": [],
        "report info: list of Filter clauses": [],
        "report info: list of Compare clause types": ["events"],
        "report info: # of Cohort clauses": 0,
        "report info: # of Negated Cohort clauses": 0,
        "report info: # of Inverse Cohort Pairs": 0,
        "report info: # of Compare clauses": 1,
        "report info: # of Group By clauses": 0,
        "report info: # of Filter clauses": 0,
        "report info: # of formulas": 0,
        "report info: # of Segments": 0,
        "report info: time aggregation unit": "day",
        "report info: time window unit": "day",
        "report info: time window value": 30,
        "report info: time from date": null,
        "report info: time to date": null,
        "report info: date range type": "in the last",
        "report info: number of days queried": 30,
        "report info: uses cohorts": false,
        "report info: uses cohorts over time": false,
        "report info: # of custom events used": 0,
        num_group_by_custom_properties: 0,
        Email: "ryan.hirsch@mixpanel.com",
        project_id: "4",
        "User ID": 1732309,
        token: "2fd54f3085a7b7d70da94096fc415078"
      }
    },
    {
      sentAt: 1566697827081,
      domain: "https://mixpanel.com",
      event: "[Insights] Query Start",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697827.078,
        distinct_id: "1732309",
        $device_id:
          "16c4963be70358-01cba8675d339d-37607c05-384000-16c4963be71ce1",
        origin_referrer: '"https://mixpanel.com/"',
        origin_domain: "mixpanel.com",
        $user_id: "1732309",
        user_id: 1732309,
        "Project owner billing account ID": 1,
        "first touch landing page url": "https://mixpanel.com/settings/account",
        "Device Pixel Ratio (is it retina?)": 2,
        "Viewport Width": 1356,
        "Viewport Height": 640,
        is_invited_user: false,
        churn_canary_experiment: "churn_canary_b",
        "Billing: events/MTU plan ID": 15803,
        "Billing: events/MTU plan name":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Billing: people plan ID": 13928,
        "Billing: people plan name": "MTU - People",
        "Billing: events/MTU plan term length": 1,
        "Billing: people plan term length": 12,
        "Billing: paid plan types": "events & people",
        "Billing: events/MTU plan ARR": 0,
        "Billing: people plan ARR": 0,
        "Billing: total account ARR": 0,
        "Billing: account status": "unpaid",
        "Billing: MTU add-on packages": [
          "datawarehouse_export_v1",
          "groups_v1"
        ],
        "Billing: services plan ARR": 0,
        "Current Events Plan":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Current People Plan": "MTU - People",
        "Events Plan Value (ARR)": 0,
        "People Plan Value (ARR)": 0,
        "Account Value (ARR)": 0,
        "Events Billing Cycle": "Monthly",
        "People Billing Cycle": "Annual",
        project_id: "4",
        Email: "ryan.hirsch@mixpanel.com",
        "Project Role": "Owner",
        "Date Joined": "05/2019",
        "3-month Pricing Plan Experiment Group": "pricing_page_control1",
        "OOTB Experiment Group": "ootb_control1",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        role: "owner",
        "# of cohorts": 214,
        "VWO Experiments": [],
        $search_engine: "google",
        "Page Name": "customers",
        Platform: "Web",
        "Data Group Id": null,
        "Segment by a group property": false,
        "Filter by a group property": false,
        "Report name": "insights",
        "report info: title": "",
        "report info: datasets": [],
        "report info: using new query builder": true,
        "report info: # of datasets": 0,
        "report info: type": "line",
        "report info: style": "standard",
        "report info: analysis": "linear",
        "report info: value": "absolute",
        "report info: list of Cohort clauses": [],
        "report info: list of Compare clauses": ["$top_events"],
        "report info: list of Compare operators": ["total"],
        "report info: list of Group By clauses": [],
        "report info: list of Custom Property Group By clauses": [],
        "report info: list of Filter clauses": [],
        "report info: list of Compare clause types": ["events"],
        "report info: # of Cohort clauses": 0,
        "report info: # of Negated Cohort clauses": 0,
        "report info: # of Inverse Cohort Pairs": 0,
        "report info: # of Compare clauses": 1,
        "report info: # of Group By clauses": 0,
        "report info: # of Filter clauses": 0,
        "report info: # of formulas": 0,
        "report info: # of Segments": 0,
        "report info: time aggregation unit": "day",
        "report info: time window unit": "day",
        "report info: time window value": 30,
        "report info: time from date": null,
        "report info: time to date": null,
        "report info: date range type": "in the last",
        "report info: number of days queried": 30,
        "report info: uses cohorts": false,
        "report info: uses cohorts over time": false,
        "report info: # of custom events used": 0,
        num_group_by_custom_properties: 0,
        token: "metrics-1"
      }
    },
    {
      sentAt: 1566697827124,
      domain: "https://mixpanel.com",
      event: "Report Loaded",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697827.12,
        distinct_id: "1732309",
        $device_id:
          "16c4963be70358-01cba8675d339d-37607c05-384000-16c4963be71ce1",
        origin_referrer: '"https://mixpanel.com/"',
        origin_domain: "mixpanel.com",
        $user_id: "1732309",
        user_id: 1732309,
        "Project owner billing account ID": 1,
        "first touch landing page url": "https://mixpanel.com/settings/account",
        "Device Pixel Ratio (is it retina?)": 2,
        "Viewport Width": 1356,
        "Viewport Height": 640,
        is_invited_user: false,
        churn_canary_experiment: "churn_canary_b",
        "Billing: events/MTU plan ID": 15803,
        "Billing: events/MTU plan name":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Billing: people plan ID": 13928,
        "Billing: people plan name": "MTU - People",
        "Billing: events/MTU plan term length": 1,
        "Billing: people plan term length": 12,
        "Billing: paid plan types": "events & people",
        "Billing: events/MTU plan ARR": 0,
        "Billing: people plan ARR": 0,
        "Billing: total account ARR": 0,
        "Billing: account status": "unpaid",
        "Billing: MTU add-on packages": [
          "datawarehouse_export_v1",
          "groups_v1"
        ],
        "Billing: services plan ARR": 0,
        "Current Events Plan":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Current People Plan": "MTU - People",
        "Events Plan Value (ARR)": 0,
        "People Plan Value (ARR)": 0,
        "Account Value (ARR)": 0,
        "Events Billing Cycle": "Monthly",
        "People Billing Cycle": "Annual",
        project_id: 4,
        Email: "ryan.hirsch@mixpanel.com",
        "Project Role": "Owner",
        "Date Joined": "05/2019",
        "3-month Pricing Plan Experiment Group": "pricing_page_control1",
        "OOTB Experiment Group": "ootb_control1",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        role: "owner",
        "# of cohorts": 214,
        "VWO Experiments": [],
        $search_engine: "google",
        "Page Name": "customers",
        Platform: "Web",
        tab: "insights",
        location_href: "https://mixpanel.com/report/4/insights",
        location_host: "mixpanel.com",
        location_hash: "",
        location_path: "/report/4/insights",
        location_path_pattern: "/report/<id>/insights",
        page_redirect_ms: 0,
        page_tcp_setup_ms: 207,
        page_first_byte_ms: 692,
        page_dom_content_loaded_ms: 1754,
        page_load_ms: 428,
        page_time_to_first_byte_ms: 899,
        page_time_to_dom_content_loaded_ms: 2653,
        page_time_to_load_ms: 3081,
        page_navigation_timing: {
          navigationStart: 0,
          unloadEventStart: 907,
          unloadEventEnd: 908,
          redirectStart: 0,
          redirectEnd: 0,
          fetchStart: 28,
          domainLookupStart: 30,
          domainLookupEnd: 30,
          connectStart: 30,
          connectEnd: 207,
          secureConnectionStart: 30,
          requestStart: 207,
          responseStart: 899,
          responseEnd: 964,
          domLoading: 915,
          domInteractive: 2653,
          domContentLoadedEventStart: 2653,
          domContentLoadedEventEnd: 2729,
          domComplete: 3080,
          loadEventStart: 3081,
          loadEventEnd: 0
        },
        server_response_ms: 538,
        page_time_to_first_contentful_paint_ms: 1825,
        app_time_to_init_ms: 2307,
        app_init_ms: 345,
        page_time_to_ui_ready_ms: 2932,
        memory_used_js_heap_mb: 133,
        response_count_total: 61,
        response_transfer_time_total: 11708,
        response_transfer_size_total: 111884,
        response_decoded_size_total: 752334,
        response_count_cdn4_mxpnl: 23,
        response_transfer_time_cdn4_mxpnl: 3067,
        response_transfer_size_cdn4_mxpnl: 0,
        response_decoded_size_cdn4_mxpnl: 0,
        response_count_type_css: 8,
        response_transfer_time_type_css: 630,
        response_transfer_size_type_css: 0,
        response_decoded_size_type_css: 0,
        response_count_type_js: 18,
        response_transfer_time_type_js: 3214,
        response_transfer_size_type_js: 18953,
        response_decoded_size_type_js: 62625,
        response_count_type_other: 1,
        response_transfer_time_type_other: 76,
        response_transfer_size_type_other: 0,
        response_decoded_size_type_other: 0,
        response_count_external: 4,
        response_transfer_time_external: 854,
        response_transfer_size_external: 18953,
        response_decoded_size_external: 62625,
        response_count_api_mixpanel: 23,
        response_transfer_time_api_mixpanel: 1894,
        response_transfer_size_api_mixpanel: 0,
        response_decoded_size_api_mixpanel: 0,
        response_count_type_fetch: 33,
        response_transfer_time_type_fetch: 6823,
        response_transfer_size_type_fetch: 50410,
        response_decoded_size_type_fetch: 526823,
        response_count_mixpanel: 11,
        response_transfer_time_mixpanel: 5894,
        response_transfer_size_mixpanel: 92931,
        response_decoded_size_mixpanel: 689709,
        response_count_type_page: 1,
        response_transfer_time_type_page: 964,
        response_transfer_size_type_page: 42521,
        response_decoded_size_type_page: 162886,
        token: "metrics-1"
      }
    },
    {
      sentAt: 1566697827126,
      domain: "https://mixpanel.com",
      event: "report-loaded",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697827.123,
        distinct_id: 4,
        $device_id:
          "16c4963c15d24f-03f54f6e8918af-37607c05-384000-16c4963c15e1181",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        project_id: 4,
        tab: "insights",
        location_href: "https://mixpanel.com/report/4/insights",
        location_host: "mixpanel.com",
        location_hash: "",
        location_path: "/report/4/insights",
        location_path_pattern: "/report/<id>/insights",
        page_redirect_ms: 0,
        page_tcp_setup_ms: 207,
        page_first_byte_ms: 692,
        page_dom_content_loaded_ms: 1754,
        page_load_ms: 428,
        page_time_to_first_byte_ms: 899,
        page_time_to_dom_content_loaded_ms: 2653,
        page_time_to_load_ms: 3081,
        page_navigation_timing: {
          navigationStart: 0,
          unloadEventStart: 907,
          unloadEventEnd: 908,
          redirectStart: 0,
          redirectEnd: 0,
          fetchStart: 28,
          domainLookupStart: 30,
          domainLookupEnd: 30,
          connectStart: 30,
          connectEnd: 207,
          secureConnectionStart: 30,
          requestStart: 207,
          responseStart: 899,
          responseEnd: 964,
          domLoading: 915,
          domInteractive: 2653,
          domContentLoadedEventStart: 2653,
          domContentLoadedEventEnd: 2729,
          domComplete: 3080,
          loadEventStart: 3081,
          loadEventEnd: 0
        },
        server_response_ms: 538,
        page_time_to_first_contentful_paint_ms: 1825,
        app_time_to_init_ms: 2307,
        app_init_ms: 345,
        page_time_to_ui_ready_ms: 2932,
        memory_used_js_heap_mb: 133,
        response_count_total: 61,
        response_transfer_time_total: 11708,
        response_transfer_size_total: 111884,
        response_decoded_size_total: 752334,
        response_count_cdn4_mxpnl: 23,
        response_transfer_time_cdn4_mxpnl: 3067,
        response_transfer_size_cdn4_mxpnl: 0,
        response_decoded_size_cdn4_mxpnl: 0,
        response_count_type_css: 8,
        response_transfer_time_type_css: 630,
        response_transfer_size_type_css: 0,
        response_decoded_size_type_css: 0,
        response_count_type_js: 18,
        response_transfer_time_type_js: 3214,
        response_transfer_size_type_js: 18953,
        response_decoded_size_type_js: 62625,
        response_count_type_other: 1,
        response_transfer_time_type_other: 76,
        response_transfer_size_type_other: 0,
        response_decoded_size_type_other: 0,
        response_count_external: 4,
        response_transfer_time_external: 854,
        response_transfer_size_external: 18953,
        response_decoded_size_external: 62625,
        response_count_api_mixpanel: 23,
        response_transfer_time_api_mixpanel: 1894,
        response_transfer_size_api_mixpanel: 0,
        response_decoded_size_api_mixpanel: 0,
        response_count_type_fetch: 33,
        response_transfer_time_type_fetch: 6823,
        response_transfer_size_type_fetch: 50410,
        response_decoded_size_type_fetch: 526823,
        response_count_mixpanel: 11,
        response_transfer_time_mixpanel: 5894,
        response_transfer_size_mixpanel: 92931,
        response_decoded_size_mixpanel: 689709,
        response_count_type_page: 1,
        response_transfer_time_type_page: 964,
        response_transfer_size_type_page: 42521,
        response_decoded_size_type_page: 162886,
        token: "a97d6abb431eaf5735b8ba5688590bc2"
      }
    },
    {
      sentAt: 1566697828795,
      domain: "https://mixpanel.com",
      event: "app.frontend.reports.tti",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697828.792,
        distinct_id:
          "16c4963be773d0-053e39a48e20b6-37607c05-384000-16c4963be78d75",
        $device_id:
          "16c4963be773d0-053e39a48e20b6-37607c05-384000-16c4963be78d75",
        project_id: "4",
        "report name": "insights",
        user_id: "1732309",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        "tti milliseconds": 2971,
        token: "f23d0bc4403e457a3cff2c0beade83ca"
      }
    },
    {
      sentAt: 1566697828800,
      domain: "https://mixpanel.com",
      event: "Query Finish",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697828.798,
        distinct_id: 1732309,
        $device_id:
          "16c4963be8165b-06547b21ec22f5-37607c05-384000-16c4963be82ba8",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        $user_id: 1732309,
        "report info: title": "",
        "report info: datasets": [],
        "report info: using new query builder": true,
        "report info: # of datasets": 0,
        "report info: type": "line",
        "report info: style": "standard",
        "report info: analysis": "linear",
        "report info: value": "absolute",
        "report info: list of Cohort clauses": [],
        "report info: list of Compare clauses": ["$top_events"],
        "report info: list of Compare operators": ["total"],
        "report info: list of Group By clauses": [],
        "report info: list of Custom Property Group By clauses": [],
        "report info: list of Filter clauses": [],
        "report info: list of Compare clause types": ["events"],
        "report info: # of Cohort clauses": 0,
        "report info: # of Negated Cohort clauses": 0,
        "report info: # of Inverse Cohort Pairs": 0,
        "report info: # of Compare clauses": 1,
        "report info: # of Group By clauses": 0,
        "report info: # of Filter clauses": 0,
        "report info: # of formulas": 0,
        "report info: # of Segments": 12,
        "report info: time aggregation unit": "day",
        "report info: time window unit": "day",
        "report info: time window value": 30,
        "report info: time from date": null,
        "report info: time to date": null,
        "report info: date range type": "in the last",
        "report info: number of days queried": 30,
        "report info: uses cohorts": false,
        "report info: uses cohorts over time": false,
        "report info: # of custom events used": 0,
        num_group_by_custom_properties: 0,
        "latency ms": 1715,
        "report info: minimum sampling rate": 1,
        Email: "ryan.hirsch@mixpanel.com",
        project_id: "4",
        "User ID": 1732309,
        token: "2fd54f3085a7b7d70da94096fc415078"
      }
    },
    {
      sentAt: 1566697828802,
      domain: "https://mixpanel.com",
      event: "[Insights] Query Finish",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://mixpanel.com/report/4/insights",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697828.8,
        distinct_id: "1732309",
        $device_id:
          "16c4963be70358-01cba8675d339d-37607c05-384000-16c4963be71ce1",
        origin_referrer: '"https://mixpanel.com/"',
        origin_domain: "mixpanel.com",
        $user_id: "1732309",
        user_id: 1732309,
        "Project owner billing account ID": 1,
        "first touch landing page url": "https://mixpanel.com/settings/account",
        "Device Pixel Ratio (is it retina?)": 2,
        "Viewport Width": 1356,
        "Viewport Height": 640,
        is_invited_user: false,
        churn_canary_experiment: "churn_canary_b",
        "Billing: events/MTU plan ID": 15803,
        "Billing: events/MTU plan name":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Billing: people plan ID": 13928,
        "Billing: people plan name": "MTU - People",
        "Billing: events/MTU plan term length": 1,
        "Billing: people plan term length": 12,
        "Billing: paid plan types": "events & people",
        "Billing: events/MTU plan ARR": 0,
        "Billing: people plan ARR": 0,
        "Billing: total account ARR": 0,
        "Billing: account status": "unpaid",
        "Billing: MTU add-on packages": [
          "datawarehouse_export_v1",
          "groups_v1"
        ],
        "Billing: services plan ARR": 0,
        "Current Events Plan":
          "Free Trial - Enterprise AB Testing (MARKETING) Aug 2018",
        "Current People Plan": "MTU - People",
        "Events Plan Value (ARR)": 0,
        "People Plan Value (ARR)": 0,
        "Account Value (ARR)": 0,
        "Events Billing Cycle": "Monthly",
        "People Billing Cycle": "Annual",
        project_id: "4",
        Email: "ryan.hirsch@mixpanel.com",
        "Project Role": "Owner",
        "Date Joined": "05/2019",
        "3-month Pricing Plan Experiment Group": "pricing_page_control1",
        "OOTB Experiment Group": "ootb_control1",
        $initial_referrer: "https://mixpanel.com/report/3/insights",
        $initial_referring_domain: "mixpanel.com",
        role: "owner",
        "# of cohorts": 214,
        "VWO Experiments": [],
        $search_engine: "google",
        "Page Name": "customers",
        Platform: "Web",
        "report info: title": "",
        "report info: datasets": [],
        "report info: using new query builder": true,
        "report info: # of datasets": 0,
        "report info: type": "line",
        "report info: style": "standard",
        "report info: analysis": "linear",
        "report info: value": "absolute",
        "report info: list of Cohort clauses": [],
        "report info: list of Compare clauses": ["$top_events"],
        "report info: list of Compare operators": ["total"],
        "report info: list of Group By clauses": [],
        "report info: list of Custom Property Group By clauses": [],
        "report info: list of Filter clauses": [],
        "report info: list of Compare clause types": ["events"],
        "report info: # of Cohort clauses": 0,
        "report info: # of Negated Cohort clauses": 0,
        "report info: # of Inverse Cohort Pairs": 0,
        "report info: # of Compare clauses": 1,
        "report info: # of Group By clauses": 0,
        "report info: # of Filter clauses": 0,
        "report info: # of formulas": 0,
        "report info: # of Segments": 12,
        "report info: time aggregation unit": "day",
        "report info: time window unit": "day",
        "report info: time window value": 30,
        "report info: time from date": null,
        "report info: time to date": null,
        "report info: date range type": "in the last",
        "report info: number of days queried": 30,
        "report info: uses cohorts": false,
        "report info: uses cohorts over time": false,
        "report info: # of custom events used": 0,
        num_group_by_custom_properties: 0,
        "latency ms": 1715,
        "report info: minimum sampling rate": 1,
        token: "metrics-1"
      }
    },
    {
      sentAt: 1566697835032,
      domain: "https://design.mixpanel.com",
      event: "Viewed design.mixpanel.com",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://design.mixpanel.com/#mp-table",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697835.03,
        distinct_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $device_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        token: "9c4e9a6caf9f429a7e3821141fc769b7"
      }
    },
    {
      sentAt: 1566697835036,
      domain: "https://design.mixpanel.com",
      event: "mp_page_view",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://design.mixpanel.com/#mp-table",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697835.032,
        distinct_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $device_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        mp_page: "https://design.mixpanel.com/#mp-table",
        mp_browser: "Chrome",
        mp_platform: "Mac OS X",
        token: "9c4e9a6caf9f429a7e3821141fc769b7"
      }
    },
    {
      sentAt: 1566697838116,
      domain: "https://design.mixpanel.com",
      event: "[mp-table] Load",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://design.mixpanel.com/#mp-table",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697838.115,
        distinct_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $device_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        name: "design-system-example",
        durationMs: 2466,
        numRows: 1532,
        token: "9c4e9a6caf9f429a7e3821141fc769b7"
      }
    },
    {
      sentAt: 1566697838356,
      domain: "https://design.mixpanel.com",
      event: "Smart Hub: Clicked",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://design.mixpanel.com/#mp-table",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697838.355,
        distinct_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $device_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        display_context: "GLOBAL",
        project_id: "3",
        bookmark_id: 0,
        page_number: 2,
        token: "9c4e9a6caf9f429a7e3821141fc769b7"
      }
    },
    {
      sentAt: 1566697839586,
      domain: "https://design.mixpanel.com",
      event: "[mp-table] Selection Change",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://design.mixpanel.com/#mp-table",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697839.585,
        distinct_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $device_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        name: "design-system-example",
        isSelected: true,
        numChanged: 1532,
        toggleAll: true,
        token: "9c4e9a6caf9f429a7e3821141fc769b7"
      }
    },
    {
      sentAt: 1566697839928,
      domain: "https://design.mixpanel.com",
      event: "[mp-table] Selection Change",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://design.mixpanel.com/#mp-table",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.29.1",
        time: 1566697839.927,
        distinct_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $device_id:
          "16b908c5160390-0c42755b34205c-37647e05-384000-16b908c51618bd",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        name: "design-system-example",
        isSelected: false,
        numChanged: 1532,
        toggleAll: true,
        token: "9c4e9a6caf9f429a7e3821141fc769b7"
      }
    },
    {
      sentAt: 1566697844039,
      domain: "https://jvsbarandgrill.com",
      event: "Page View",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://jvsbarandgrill.com/",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.28.0",
        time: 1566697844.037,
        distinct_id:
          "16cc5fc38a252f-09ea38d5abaf2-38637706-232800-16cc5fc38a394c",
        $device_id:
          "16cc5fc38a252f-09ea38d5abaf2-38637706-232800-16cc5fc38a394c",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        replace: {},
        href: "https://jvsbarandgrill.com/",
        ancestorOrigins: {},
        origin: "https://jvsbarandgrill.com",
        protocol: "https:",
        host: "jvsbarandgrill.com",
        hostname: "jvsbarandgrill.com",
        port: "",
        pathname: "/",
        search: "",
        hash: "",
        assign: {},
        reload: {},
        toString: {},
        state: null,
        key: "initial",
        token: "af41a95bfb27680b4573da54ab732053"
      }
    },
    {
      sentAt: 1566697847393,
      domain: "https://jvsbarandgrill.com",
      event: "View Menu",
      properties: {
        $os: "Mac OS X",
        $browser: "Chrome",
        $current_url: "https://jvsbarandgrill.com/menu",
        $browser_version: 76,
        $screen_height: 1200,
        $screen_width: 1920,
        mp_lib: "web",
        $lib_version: "2.28.0",
        time: 1566697847.391,
        distinct_id:
          "16cc5fc38a252f-09ea38d5abaf2-38637706-232800-16cc5fc38a394c",
        $device_id:
          "16cc5fc38a252f-09ea38d5abaf2-38637706-232800-16cc5fc38a394c",
        $initial_referrer: "$direct",
        $initial_referring_domain: "$direct",
        token: "af41a95bfb27680b4573da54ab732053"
      }
    }
  ],
  domains: {
    "https://mixpanel.com": 14,
    "https://design.mixpanel.com": 6,
    "https://jvsbarandgrill.com": 3
  }
};
